PARQUERT_DIR = "parquet_files"
DUCKDB_PATH = "us_campaign_finance.duckdb"

BASE_URL = "https://www.fec.gov/files/bulk-downloads/"
S3_BUCKET_NAME = "cg-519a459a-0ea3-42c2-b7bc-fa1143481f74"
S3_REGION_NAME = "us-gov-west-1"
ELECTRONIC_FEC_PREFIX = "bulk-downloads/electronic/"

METADATA = [
    dict(category="all_candidates", year="2024", remainder="2024/weball24.zip"),
    dict(category="candidate_master", year="2024", remainder="2024/cn24.zip"),
    dict(
        category="candidate_committee_linkage", year="2024", remainder="2024/ccl24.zip"
    ),
    dict(category="house_senate", year="2024", remainder="2024/webl24.zip"),
    dict(category="committee_master", year="2024", remainder="2024/cm24.zip"),
    dict(category="pac_summary", year="2024", remainder="2024/webk24.zip"),
]

COLUMNS = {
    "all_candidates": [
        "CAND_ID",
        "CAND_NAME",
        "CAND_ICI",
        "PTY_CD",
        "CAND_PTY_AFFILIATION",
        "TTL_RECEIPTS",
        "TRANS_FROM_AUTH",
        "TTL_DISB",
        "TRANS_TO_AUTH",
        "COH_BOP",
        "COH_COP",
        "CAND_CONTRIB",
        "CAND_LOANS",
        "OTHER_LOANS",
        "CAND_LOAN_REPAY",
        "OTHER_LOAN_REPAY",
        "DEBTS_OWED_BY",
        "TTL_INDIV_CONTRIB",
        "CAND_OFFICE_ST",
        "CAND_OFFICE_DISTRICT",
        "SPEC_ELECTION",
        "PRIM_ELECTION",
        "RUN_ELECTION",
        "GEN_ELECTION",
        "GEN_ELECTION_PRECENT",
        "OTHER_POL_CMTE_CONTRIB",
        "POL_PTY_CONTRIB",
        "CVG_END_DT",
        "INDIV_REFUNDS",
        "CMTE_REFUNDS",
    ],
    "candidate_master": [
        "CAND_ID",
        "CAND_NAME",
        "CAND_PTY_AFFILIATION",
        "CAND_ELECTION_YR",
        "CAND_OFFICE_ST",
        "CAND_OFFICE",
        "CAND_OFFICE_DISTRICT",
        "CAND_ICI",
        "CAND_STATUS",
        "CAND_PCC",
        "CAND_ST1",
        "CAND_ST2",
        "CAND_CITY",
        "CAND_ST",
        "CAND_ZIP",
    ],
    "candidate_committee_linkage": [
        "CAND_ID",
        "CAND_ELECTION_YR",
        "FEC_ELECTION_YR",
        "CMTE_ID",
        "CMTE_TP",
        "CMTE_DSGN",
        "LINKAGE_ID",
    ],
    "house_senate": [
        "CAND_ID",
        "CAND_NAME",
        "CAND_ICI",
        "PTY_CD",
        "CAND_PTY_AFFILIATION",
        "TTL_RECEIPTS",
        "TRANS_FROM_AUTH",
        "TTL_DISB",
        "TRANS_TO_AUTH",
        "COH_BOP",
        "COH_COP",
        "CAND_CONTRIB",
        "CAND_LOANS",
        "OTHER_LOANS",
        "CAND_LOAN_REPAY",
        "OTHER_LOAN_REPAY",
        "DEBTS_OWED_BY",
        "TTL_INDIV_CONTRIB",
        "CAND_OFFICE_ST",
        "CAND_OFFICE_DISTRICT",
        "SPEC_ELECTION",
        "PRIM_ELECTION",
        "RUN_ELECTION",
        "GEN_ELECTION",
        "GEN_ELECTION_PRECENT",
        "OTHER_POL_CMTE_CONTRIB",
        "POL_PTY_CONTRIB",
        "CVG_END_DT",
        "INDIV_REFUNDS",
        "CMTE_REFUNDS",
    ],
    "committee_master": [
        "CMTE_ID",
        "CMTE_NM",
        "TRES_NM",
        "CMTE_ST1",
        "CMTE_ST2",
        "CMTE_CITY",
        "CMTE_ST",
        "CMTE_ZIP",
        "CMTE_DSGN",
        "CMTE_TP",
        "CMTE_PTY_AFFILIATION",
        "CMTE_FILING_FREQ",
        "ORG_TP",
        "CONNECTED_ORG_NM",
        "CAND_ID",
    ],
    "pac_summary": [
        "CMTE_ID",
        "CMTE_NM",
        "CMTE_TP",
        "CMTE_DSGN",
        "CMTE_FILING_FREQ",
        "TTL_RECEIPTS",
        "TRANS_FROM_AFF",
        "INDV_CONTRIB",
        "OTHER_POL_CMTE_CONTRIB",
        "CAND_CONTRIB",
        "CAND_LOANS",
        "TTL_LOANS_RECEIVED",
        "TTL_DISB",
        "TRANF_TO_AFF",
        "INDV_REFUNDS",
        "OTHER_POL_CMTE_REFUNDS",
        "CAND_LOAN_REPAY",
        "LOAN_REPAY",
        "COH_BOP",
        "COH_COP",
        "DEBTS_OWED_BY",
        "NONFED_TRANS_RECEIVED",
        "CONTRIB_TO_OTHER_CMTE",
        "IND_EXP",
        "PTY_COORD_EXP",
        "NONFED_SHARE_EXP",
        "CVG_END_DT",
    ],
}
