DATARECCE_TODOFEC_S3_BUCKET_NAME = "datarecce-todofec"
DATARECCE_TODOFEC_S3_REGION_NAME = "us-east-1"
RAW_DATA_DIR = "datarecce-todofec"
PARQUERT_DIR = "datarecce-todofec"

BASE_URL = "https://www.fec.gov/files/bulk-downloads/"
S3_BUCKET_NAME = "cg-519a459a-0ea3-42c2-b7bc-fa1143481f74"
S3_REGION_NAME = "us-gov-west-1"
ELECTRONIC_FEC_PREFIX = "bulk-downloads/electronic/"

METADATA = [
    dict(category="all_candidates", year="2024", remainder="2024/weball24.zip"),
    dict(category="all_candidates", year="2020", remainder="2020/weball20.zip"),
    dict(category="candidate_master", year="2024", remainder="2024/cn24.zip"),
    dict(
        category="candidate_committee_linkage", year="2024", remainder="2024/ccl24.zip"
    ),
    dict(category="house_senate", year="2024", remainder="2024/webl24.zip"),
    dict(category="committee_master", year="2024", remainder="2024/cm24.zip"),
    dict(category="pac_summary", year="2024", remainder="2024/webk24.zip"),
    # Skip this one, the zip file too large (2.86 GB)
    # dict(
    #     category="contributions_by_individuals",
    #     year="2024",
    #     remainder="2024/indiv24.zip",
    # ),
    dict(
        category="contributions_from_committees_to_candidates",
        year="2024",
        remainder="2024/pas224.zip",
    ),
    dict(
        category="contributions_from_committees_to_candidates",
        year="2020",
        remainder="2020/pas220.zip",
    ),
    # Skip this one, the zip file too large (320.7 BB)
    # dict(
    #     category="transactions_between_committees",
    #     year="2024",
    #     remainder="2024/oth24.zip",
    # ),
    dict(category="operating_expenditures", year="2024", remainder="2024/oppexp24.zip"),
]

COLUMNS = {
    "all_candidates": [
        "CAND_ID",
        "CAND_NAME",
        "CAND_ICI",
        "PTY_CD",
        "CAND_PTY_AFFILIATION",
        "TTL_RECEIPTS",
        "TRANS_FROM_AUTH",
        "TTL_DISB",
        "TRANS_TO_AUTH",
        "COH_BOP",
        "COH_COP",
        "CAND_CONTRIB",
        "CAND_LOANS",
        "OTHER_LOANS",
        "CAND_LOAN_REPAY",
        "OTHER_LOAN_REPAY",
        "DEBTS_OWED_BY",
        "TTL_INDIV_CONTRIB",
        "CAND_OFFICE_ST",
        "CAND_OFFICE_DISTRICT",
        "SPEC_ELECTION",
        "PRIM_ELECTION",
        "RUN_ELECTION",
        "GEN_ELECTION",
        "GEN_ELECTION_PRECENT",
        "OTHER_POL_CMTE_CONTRIB",
        "POL_PTY_CONTRIB",
        "CVG_END_DT",
        "INDIV_REFUNDS",
        "CMTE_REFUNDS",
    ],
    "candidate_master": [
        "CAND_ID",
        "CAND_NAME",
        "CAND_PTY_AFFILIATION",
        "CAND_ELECTION_YR",
        "CAND_OFFICE_ST",
        "CAND_OFFICE",
        "CAND_OFFICE_DISTRICT",
        "CAND_ICI",
        "CAND_STATUS",
        "CAND_PCC",
        "CAND_ST1",
        "CAND_ST2",
        "CAND_CITY",
        "CAND_ST",
        "CAND_ZIP",
    ],
    "candidate_committee_linkage": [
        "CAND_ID",
        "CAND_ELECTION_YR",
        "FEC_ELECTION_YR",
        "CMTE_ID",
        "CMTE_TP",
        "CMTE_DSGN",
        "LINKAGE_ID",
    ],
    "house_senate": [
        "CAND_ID",
        "CAND_NAME",
        "CAND_ICI",
        "PTY_CD",
        "CAND_PTY_AFFILIATION",
        "TTL_RECEIPTS",
        "TRANS_FROM_AUTH",
        "TTL_DISB",
        "TRANS_TO_AUTH",
        "COH_BOP",
        "COH_COP",
        "CAND_CONTRIB",
        "CAND_LOANS",
        "OTHER_LOANS",
        "CAND_LOAN_REPAY",
        "OTHER_LOAN_REPAY",
        "DEBTS_OWED_BY",
        "TTL_INDIV_CONTRIB",
        "CAND_OFFICE_ST",
        "CAND_OFFICE_DISTRICT",
        "SPEC_ELECTION",
        "PRIM_ELECTION",
        "RUN_ELECTION",
        "GEN_ELECTION",
        "GEN_ELECTION_PRECENT",
        "OTHER_POL_CMTE_CONTRIB",
        "POL_PTY_CONTRIB",
        "CVG_END_DT",
        "INDIV_REFUNDS",
        "CMTE_REFUNDS",
    ],
    "committee_master": [
        "CMTE_ID",
        "CMTE_NM",
        "TRES_NM",
        "CMTE_ST1",
        "CMTE_ST2",
        "CMTE_CITY",
        "CMTE_ST",
        "CMTE_ZIP",
        "CMTE_DSGN",
        "CMTE_TP",
        "CMTE_PTY_AFFILIATION",
        "CMTE_FILING_FREQ",
        "ORG_TP",
        "CONNECTED_ORG_NM",
        "CAND_ID",
    ],
    "pac_summary": [
        "CMTE_ID",
        "CMTE_NM",
        "CMTE_TP",
        "CMTE_DSGN",
        "CMTE_FILING_FREQ",
        "TTL_RECEIPTS",
        "TRANS_FROM_AFF",
        "INDV_CONTRIB",
        "OTHER_POL_CMTE_CONTRIB",
        "CAND_CONTRIB",
        "CAND_LOANS",
        "TTL_LOANS_RECEIVED",
        "TTL_DISB",
        "TRANF_TO_AFF",
        "INDV_REFUNDS",
        "OTHER_POL_CMTE_REFUNDS",
        "CAND_LOAN_REPAY",
        "LOAN_REPAY",
        "COH_BOP",
        "COH_COP",
        "DEBTS_OWED_BY",
        "NONFED_TRANS_RECEIVED",
        "CONTRIB_TO_OTHER_CMTE",
        "IND_EXP",
        "PTY_COORD_EXP",
        "NONFED_SHARE_EXP",
        "CVG_END_DT",
    ],
    "contributions_by_individuals": [
        "CMTE_ID",
        "AMNDT_IND",
        "RPT_TP",
        "TRANSACTION_PGI",
        "IMAGE_NUM",
        "TRANSACTION_TP",
        "ENTITY_TP",
        "NAME",
        "CITY",
        "STATE",
        "ZIP_CODE",
        "EMPLOYER",
        "OCCUPATION",
        "TRANSACTION_DT",
        "TRANSACTION_AMT",
        "OTHER_ID",
        "TRAN_ID",
        "FILE_NUM",
        "MEMO_CD",
        "MEMO_TEXT",
        "SUB_ID",
    ],
    "contributions_from_committees_to_candidates": [
        "CMTE_ID",
        "AMNDT_IND",
        "RPT_TP",
        "TRANSACTION_PGI",
        "IMAGE_NUM",
        "TRANSACTION_TP",
        "ENTITY_TP",
        "NAME",
        "CITY",
        "STATE",
        "ZIP_CODE",
        "EMPLOYER",
        "OCCUPATION",
        "TRANSACTION_DT",
        "TRANSACTION_AMT",
        "OTHER_ID",
        "CAND_ID",
        "TRAN_ID",
        "FILE_NUM",
        "MEMO_CD",
        "MEMO_TEXT",
        "SUB_ID",
    ],
    "transactions_between_committees": [
        "CMTE_ID",
        "AMNDT_IND",
        "RPT_TP",
        "TRANSACTION_PGI",
        "IMAGE_NUM",
        "TRANSACTION_TP",
        "ENTITY_TP",
        "NAME",
        "CITY",
        "STATE",
        "ZIP_CODE",
        "EMPLOYER",
        "OCCUPATION",
        "TRANSACTION_DT",
        "TRANSACTION_AMT",
        "OTHER_ID",
        "TRAN_ID",
        "FILE_NUM",
        "MEMO_CD",
        "MEMO_TEXT",
        "SUB_ID",
    ],
    "operating_expenditures": [
        "CMTE_ID",
        "AMNDT_IND",
        "RPT_YR",
        "RPT_TP",
        "IMAGE_NUM",
        "LINE_NUM",
        "FORM_TP_CD",
        "SCHED_TP_CD",
        "NAME",
        "CITY",
        "STATE",
        "ZIP_CODE",
        "TRANSACTION_DT",
        "TRANSACTION_AMT",
        "TRANSACTION_PGI",
        "PURPOSE",
        "CATEGORY",
        "CATEGORY_DESC",
        "MEMO_CD",
        "MEMO_TEXT",
        "ENTITY_TP",
        "SUB_ID",
        "FILE_NUM",
        "TRAN_ID",
        "BACK_REF_TRAN_ID",
    ],
}
